Repository utopia-rise/godot-kotlin-jvm, pull requests merged in 2022-12, with the labels that each got.

#396 Fix constructor with generic args registration
  harness/tests/src/main/kotlin/godot/tests/constructor/ConstructorRegistrationTest.kt
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/ConstructorRegistrationGenerator.kt
Labels: bug, topic:entry-gen

#393 Feature/4.0/implement vector4
  kt/godot-library/src/main/kotlin/godot/core/Variant.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector2.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector3.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector4.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector4i.kt
  kt/godot-library/src/main/kotlin/godot/util/Utils.kt
  src/kt_variant.h
Labels: GD4

#395 Fix resource property type hint
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
  kt/godot-library/src/main/kotlin/godot/core/Functions.kt
  kt/godot-library/src/main/kotlin/godot/core/VariantArray.kt
Labels: topic:entry-gen

#403 fix: engine_call_appendArray signature in packed_float_64_array_bridge.cpp
  src/memory/bridges/packed_float_64_array_bridge.cpp
Labels: bug, GD4

#404 fix: Invalid use of class index in TransferContext::create_native_object
  src/memory/transfer_context.cpp
Labels: bug, GD4

#400 feat: implement Rect2i core type kotlin class
  kt/godot-library/src/main/kotlin/godot/core/Rect2.kt
  kt/godot-library/src/main/kotlin/godot/core/Rect2i.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector2i.kt
Labels: GD4

#405 Bugfix/4.0/fixed arg count when reading args
  src/memory/bridges/callable_bridge.cpp
  src/memory/kotlin_binding.cpp
  src/memory/transfer_context.cpp
Labels: bug, GD4

#406 fix: Add missing core types to entry generator.
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
Labels: bug, GD4

#407 bugfix(4.0): Add new core types to api generation
  kt/api-generator/src/main/kotlin/godot/codegen/constants/Classes.kt
Labels: bug, GD4

#410 bugfix(4.0): replace references to godot.Reference by godot.RefCounted in entry gen and intellij plugin
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
  kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/property/RegisterPropertiesAnnotator.kt
  kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties
Labels: bug, GD4

#409 bugfix(api-gen): do camel case conversion for properties after replacing '/' bt '_'
  kt/api-generator/src/main/kotlin/godot/codegen/models/enriched/EnrichedProperty.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/AnimatedTexture.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/AnimationNodeBlendSpace1D.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/AnimationNodeBlendSpace2D.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/AnimationNodeTransition.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/AudioEffectChorus.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/AudioEffectDelay.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/CharacterBody2D.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/CharacterBody3D.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/Environment.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/Joint3D.kt
  kt/godot-library/src/main/kotlin/godot/gen/godot/NavigationMesh.kt
Labels: bug, GD4

#408 bugfix(4.0): set KotlinBinding's KtObject if owner is not RefCounted
  src/memory/kotlin_binding.cpp
Labels: bug, GD4

#412 bugfix/4.0/get-instance-binding-when-no-existing-binding
  src/memory/kotlin_binding_manager.cpp
Labels: bug, GD4

#415 chore(4.0): update module to godot 4.0 beta 10
  .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
  .github/workflows/check-pr-engine-editor-release.yaml
  .github/workflows/check-pr-engine-export-template-debug.yaml
  .github/workflows/check-pr-engine-export-template-release.yaml
  .github/workflows/check-pr-godot-kotlin-symbol-processor.yaml
  .github/workflows/deploy-export-template.yaml
  .github/workflows/deploy-godot-editor-release.yaml
  .github/workflows/deploy-godot-kotlin-symbol-processor.yaml
  .github/workflows/deploy-godot-library.yaml
  kt/godot-library/src/main/kotlin/godot/core/VariantArray.kt
  src/kotlin_editor_export_plugin.cpp
  src/memory/bridges/variant_array_bridge.cpp
  src/memory/bridges/variant_array_bridge.h
  src/memory/kotlin_binding_manager.cpp
  src/memory/kotlin_binding_manager.h
Labels: GD4
