Repository utopia-rise/godot-kotlin-jvm, pull requests merged in 2023-07, with the labels that each got.

#465 Feature/4.0/update core types
  harness/tests/scripts/godot/tests/Invocation.gdj
  harness/tests/src/main/kotlin/godot/tests/coretypes/BasisTest.kt
  kt/godot-library/src/main/kotlin/godot/core/AABB.kt
  kt/godot-library/src/main/kotlin/godot/core/Basis.kt
  kt/godot-library/src/main/kotlin/godot/core/Callable.kt
  kt/godot-library/src/main/kotlin/godot/core/Color.kt
  kt/godot-library/src/main/kotlin/godot/core/Dictionary.kt
  kt/godot-library/src/main/kotlin/godot/core/MathFuncs.kt
  kt/godot-library/src/main/kotlin/godot/core/Plane.kt
  kt/godot-library/src/main/kotlin/godot/core/Quaternion.kt
  kt/godot-library/src/main/kotlin/godot/core/Rect2.kt
  kt/godot-library/src/main/kotlin/godot/core/Rect2i.kt
  kt/godot-library/src/main/kotlin/godot/core/StringName.kt
  kt/godot-library/src/main/kotlin/godot/core/Transform2D.kt
  kt/godot-library/src/main/kotlin/godot/core/Transform3D.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector2.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector2i.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector3.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector3i.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector4.kt
  kt/godot-library/src/main/kotlin/godot/core/Vector4i.kt
  kt/godot-library/src/main/kotlin/godot/global/GDCore.kt
  kt/godot-library/src/main/kotlin/godot/util/Utils.kt
  kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/godot-kotlin-graal-jni-config.json
  src/memory/bridges/callable_bridge.cpp
  src/memory/bridges/callable_bridge.h
  src/memory/bridges/dictionary_bridge.cpp
  src/memory/bridges/dictionary_bridge.h
Labels: GD4

#468 Fix `3.x` release pipeline
  .github/workflows/create-draft-release.yaml
  .github/workflows/deploy-docs.yaml
  .github/workflows/deploy-export-template.yaml
  .github/workflows/deploy-godot-editor-release.yaml
Labels: bug, GD3

#473 [3.x] Bump version to `0.6.2`
  docs/src/doc/user-guide/versioning.md
  kt/buildSrc/src/main/kotlin/godotKotlinJvmVersion.kt
  kt/plugins/godot-intellij-plugin/src/main/resources/template/gradle-wrapper.properties.template
Labels: GD3

#476 Update documentation for godot 4
  docs/mkdocs.yml
  docs/requirements.txt
  docs/src/doc/about/alpha.md
  docs/src/doc/assets/img/attach.png
  docs/src/doc/assets/img/export_template_manager_install_from_file.png
  docs/src/doc/assets/img/export_template_manager_select_tpz.png
  docs/src/doc/assets/img/final_project_structure.png
  docs/src/doc/assets/img/open_export_template_manager.png
  docs/src/doc/contribution/build-with-csharp-support.md
  docs/src/doc/contribution/knowledge-base/artefact-differentiation.md
  docs/src/doc/contribution/knowledge-base/entry-generation.md
  docs/src/doc/contribution/setup.md
  docs/src/doc/contribution/support_for_other_jvm_based_languages.md
  docs/src/doc/develop-libraries/introduction.md
  docs/src/doc/develop-libraries/publishing.md
  docs/src/doc/develop-libraries/setup.md
  docs/src/doc/getting-started/requirements.md
  docs/src/doc/getting-started/setting-up.md
  docs/src/doc/getting-started/your-first-class.md
  docs/src/doc/index.md
  docs/src/doc/user-guide/advanced/graal-vm-native-image.md
  docs/src/doc/user-guide/advanced/kotlin-singleton.md
  docs/src/doc/user-guide/api-differences.md
  docs/src/doc/user-guide/classes.md
  docs/src/doc/user-guide/consuming-libraries.md
  docs/src/doc/user-guide/debugging.md
  docs/src/doc/user-guide/exporting.md
  docs/src/doc/user-guide/functions.md
  docs/src/doc/user-guide/properties.md
  docs/src/doc/user-guide/signals.md
Labels: topic:documentation, GD4

#480 Fix various small issues
  .github/workflows/check-pr-intellij-plugin.yaml
  .github/workflows/deploy-intellij-plugin.yaml
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/checks/DefaultConstructorCheck.kt
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
  kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/RegisteredClass.kt
  kt/godot-library/src/main/kotlin/godot/extensions/NodeExt.kt
  kt/godot-library/src/main/kotlin/godot/extensions/StringExt.kt
  kt/godot-library/src/main/kotlin/godot/extensions/StringNameExt.kt
  kt/plugins/godot-intellij-plugin/build.gradle.kts
Labels: GD4
